# Generated by Django 5.2.7 on 2025-12-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_my_follower',
            field=models.BooleanField(default=False),
        ),
    ]
